# Generated by Django 5.1.1 on 2024-10-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='apiProvider',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
