# Generated by Django 5.1.1 on 2024-10-27 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_llmprovider_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='apiProvider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='apikeys', to='chat.llmprovider'),
            preserve_default=False,
        ),
    ]
