# Generated by Django 5.1.1 on 2024-12-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_llmprovider_last_updated_llmprovider_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmprovider',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
