# Generated by Django 5.1.1 on 2024-12-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_llmprovider_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmprovider',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
