# Generated by Django 5.1.1 on 2024-12-13 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_llmprovider_hidden'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='apikey',
            name='unique_nicknames_per_user',
        ),
    ]
