# Generated by Django 5.1.1 on 2024-10-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='affiliation',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='field_of_study',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(max_length=150),
        ),
    ]
